### ISSUE TITLE
Error when starting script

### ISSUE THREAD

**Issue by DaPeace** [nooxnet/smart-meter-mbus-dlms#2]
Ive followed your instructions but now is stuck with the following error-message:

`
 node smart-meter-mbus-dlms.js
/usr/src/mbus-dlms/node_modules/config/lib/config.js:853
    throw new Error("Cannot parse config file: '" + fullFilename + "': " + e3);
    ^

Error: Cannot parse config file: '/usr/src/mbus-dlms/config/default.json5': SyntaxError: JSON5: invalid character 'b' at 5:3
    at Config.util.parseFile (/usr/src/mbus-dlms/node_modules/config/lib/config.js:853:11)
    at /usr/src/mbus-dlms/node_modules/config/lib/config.js:649:26
    at Array.forEach (<anonymous>)
    at Config.util.loadFileConfigs (/usr/src/mbus-dlms/node_modules/config/lib/config.js:648:16)
    at new Config (/usr/src/mbus-dlms/node_modules/config/lib/config.js:113:27)
    at Object.<anonymous> (/usr/src/mbus-dlms/node_modules/config/lib/config.js:1510:31)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
    at Module.load (node:internal/modules/cjs/loader:1004:32)
    at Function.Module._load (node:internal/modules/cjs/loader:839:12)

`
Can you solve this? Best Regards

**Comment by nooxnet** [comment]
The error message says that your default.json5 config file has a syntax error.

Line 5, character 3.
I assume you need  a coma at the end of the line with the "port" definition and before the "baudrate." (thus the 'b' in the error message).

**Comment by DaPeace** [comment]
Thank you very much. This script is working for me without any problems now.
